[book]
title = "BSDWIKI"
description = "A book for Freebsd starters"
authors = ["li xie"]
multilingual = false
language = "zh"
src = "src"

[rust]
edition = "2018"

[output.html]
mathjax-support = false
git-repository-url = "https://github.com/bsdwiki/mdBook/tree/main/src"
edit-url-template = "https://github.com/bsdwiki/mdBook/edit/beta/{path}"

[output.html.playground]
editable = false
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"
