[book]
title = "BSD中文社区"
description = "A demo book to test and validate changes"
authors = ["Sam"]
language = "zh"

[rust]
edition = "2018"

[output.html]
mathjax-support = false
git-repository-url = "https://github.com/bsdwiki/mdBook/tree/main/test_book"
edit-url-template = "https://github.com/bsdwiki/mdBook/edit/beta/test_book/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"
